# this is equivalent to the base electra discriminator
embedding_size: 1536
hidden_size: 1536
num_hidden_layers: 12
num_attention_heads: 12
intermediate_size: 6144
hidden_act: "gelu"
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
max_position_embeddings: 512
type_vocab_size: 2
initializer_range: 0.02
layer_norm_eps: 1e-12
summary_type: "first"
summary_use_proj: True
summary_activation: "gelu"
summary_last_dropout: 0.1
pad_token_id: 0
position_embedding_type: "absolute"
classifier_dropout: None
prenorm: False
embedding_norm_layer_type: "layer_norm"
embedding_num_groups: None 
attn_norm_layer_type: "layer_norm"
attn_num_groups: None
readout_zero_init: False
query_zero_init: False