embedding_size: 512
hidden_size: 128
num_hidden_layers: 12
num_attention_heads: 2
intermediate_size: 512
hidden_act: "gelu"
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
max_position_embeddings: 512
type_vocab_size: 2
initializer_range: 0.02
layer_norm_eps: 1e-12
summary_type: "first"
summary_use_proj: True
summary_activation: "gelu"
summary_last_dropout: 0.1
pad_token_id: 0
position_embedding_type: "absolute"
classifier_dropout: None
prenorm: False
norm_layer_type: "layer_norm"